  rm(list = ls())
  #setwd("~/Documentos/shiny-NIS")
  library(dplyr)
  library(ggplot2)
  library(stringr)
  library(rlist)
  library(dplyr)
  library(tidyr)
  library("readxl")
  library("collapsibleTree")
  library(data.table)
  library(excelR)
  library("DT")
  
# old input format
# data$Period<-as.numeric(data$Period)
# Scenarios <- as.vector(unique(data$Scenario))
# Periods<- as.vector(unique(data$Period))
# Processors<- as.vector(unique(data$Processor))
# Interfaces<- as.vector(unique(data$Interface))
# Scopes<- as.vector(unique(data$Scope))
# Level <-as.vector(unique(data$Level))
# Systems<- as.vector (unique(data$System))
# Subsystems<-as.vector(unique(data$Subsystem))
# Flow<- filter(data, data$RoegenType == "flow" | data$RoegenType == "Flow")
# Fund<- filter(data, data$RoegenType == "Fund" | data$RoegenType == "fund")
# FlowInterfaces<- as.vector(unique(Flow$Interface))
# FundInterfaces <- as.vector(unique(Fund$Interface))