setwd("~/Documentos/shiny-NIS/PIE")
library(dplyr)
library(ggplot2)
library(stringr)
library(rlist)
data <- read_excel("OUTPUTS/flow_graph_solution_biodiesel.xlsx")
Scenarios <- as.vector(unique(data$Scenario))
Periods<- as.vector(unique(data$Period))
Processors<- as.vector(unique(data$Processor))
Interfaces<- as.vector(unique(data$Interfaces))
Level <-as.vector(unique(data$Level))
